core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('account/', include('account.urls', namespace='account')),
    path('orders/', include('orders.urls', namespace='orders')),
		path('wishlist/', include('wishlist.urls', namespace='wishlist')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wishlist/urls.py
from django.urls import path

from . import views

app_name = 'wishlist'

urlpatterns = [
    path('', views.wishlist_page, name='wishlist_page'),
    path('add/', views.wishlist_add, name='wishlist_add'),
    path('delete/', views.wishlist_delete, name='wishlist_delete'),
]

wishlist/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render

from store.models import Product

from .wishlist import Wishlist


def wishlist_page(request):
    wishlist = Wishlist(request)
    return render(request, 'wishlist/wishlist.html', {'wishlist': wishlist})


def wishlist_add(request):
    wishlist = Wishlist(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id=product_id)
        wishlist.add(product=product, qty=product_qty)

        wishlistqty = wishlist.__len__()
        response = JsonResponse({'qty': wishlistqty})
        return response


def wishlist_delete(request):
    wishlist = Wishlist(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        wishlist.delete(product=product_id)

        wishlistqty = wishlist.__len__()
        wishlisttotal = wishlist.get_total_price()
        response = JsonResponse({'qty': wishlistqty, 'subtotal': wishlisttotal})
        return response

templates/wishlist/wishlist.html
{% extends "../store/base.html" %} 
{% load static %} 
{% block title %}WishList{%endblock %} 
{% block content %}
<style>
	#delete-button{
		padding-top: 30px;
	}
</style>

<main class="pt-5">
  <div class="container" style="max-width: 1000px">
    <div class="col-12">
      <h1 class="h2">Your Wishlist</h1>
    </div>
    <hr />
  </div>
  <div class="container" style="max-width: 1000px">
    
    <div class="row g-3">
      <div class="col-md-7 col-lg-8 p-0">

        {% for item in wishlist %} 
        {% with product=item.product %}

        <div class="card mb-3 border-0 product-item" data-index="{{product.id}}">
          <div class="row g-0">
            <div class="col-md-2 d-none d-md-block">
              <a href="{{ product.get_absolute_url }}"><img class="img-fluid mx-auto d-block" alt="Responsive image"
                  src="{{ product.image.url }}" /></a>
            </div>
            <div class="col-md-10 ps-md-3">
              <div class="card-body p-1">
                <a class="text-decoration-none text-reset" href="{{item.product.get_absolute_url}}">
                  <h4 class="card-text pb-3">{{product.name}}</h4>
                </a>                
                <h5><a type="button" id="delete-button" data-index="{{product.id}}" class="delete-button text-decoration-none">Delete</a></h5>
              </div>
							
            </div>
          </div>
        </div>
        {% endwith %} 
        {% endfor %}
      </div>
    </div>
    
  </div>
</main>

<script>
  $(document).on("click", ".delete-button", function (e) {
    e.preventDefault();
    var prodid = $(this).data("index");
    $.ajax({
      type: "POST",
      url: '{% url "wishlist:wishlist_delete" %}',
      data: {
        productid: $(this).data("index"),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: "post",
      },
      success: function (json) {
        $('.product-item[data-index="' + prodid + '"]').remove();

          if(json.qty == 0){
            total = 0
            subtotal = 0
          }
          else{
            total = (parseFloat(json.subtotal) + 11.50).toFixed(2);
            subtotal = json.subtotal
          }

        document.getElementById("subtotal").innerHTML = subtotal;
        document.getElementById("basket-qty").innerHTML = json.qty;
        document.getElementById("total").innerHTML = total;
      },
      error: function (xhr, errmsg, err) {},
    });
  });
</script>

{% endblock %}