account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import (PwdResetConfirmForm, PwdResetForm, UserLoginForm)

# https://docs.djangoproject.com/en/3.1/topics/auth/default/
# https://ccbv.co.uk/projects/Django/3.0/django.contrib.auth.views/PasswordResetConfirmView/

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/registration/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>)/', views.account_activate, name='activate'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/user/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm',
                                                                 email_template_name='account/user/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/user/password_reset_confirm.html',
                                                                                                success_url='/account/password_reset_complete/', 
                                                                                                form_class=PwdResetConfirmForm),
         name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_done'),
    path('password_reset_complete/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_complete'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user/', views.delete_user, name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="account/user/delete_confirm.html"), name='delete_confirmation'),
]

basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('account/', include('account.urls', namespace='account')),
    path('orders/', include('orders.urls', namespace='orders')),
		path('wishlist/', include('wishlist.urls', namespace='wishlist')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_all, name='product_all'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
    path('search_sneaker/', views.search_sneaker, name='search_sneaker'),
]

store/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='product_creator')
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', default='images/default.png')
    slug = models.SlugField(max_length=255)
    size = models.DecimalField(max_digits=2, decimal_places=0)
    price = models.DecimalField(max_digits=4, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

    def __str__(self):
        return self.name

store/views.py
from django.shortcuts import get_object_or_404, render

from .models import Category, Product


def product_all(request):
    products = Product.products.all()
    return render(request, 'store/home.html', {'products': products})


def category_list(request, category_slug=None):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(request, 'store/products/category.html', {'category': category, 'products': products})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, 'store/products/single.html', {'product': product})

def search_sneaker(request):
    if request.method == "POST":
        searched = request.POST['searched']
        sneakers = Product.objects.filter(name__contains=searched)
        return render(request, 'store/search_sneaker.html', 
        {'searched': searched,'sneakers':sneakers, } )

    else:
        return render(request, 'store/search_sneaker.html', {} )

templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %}SneakerShop{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous">
    </script>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'core/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'core/basket/css/basket.css' %}">
    <link rel="icon" href="/media/images/favicon1.ico" type="image/x-icon">
</head>

<body style="min-height: 100vh; display: flex; flex-direction: column;">
    <header style="font-family: 'Poppins', sans-serif;">
        <nav class="navbar navbar-expand-md navbar-light border-bottom" style="background-color: rgba(40, 41, 36, 1);">
            <div class="container-fluid px-md-4">
                <div class="d-flex w-100 navbar-collapse">
                    <a class="navbar-brand d-flex-inline" href="/">
                        <img src="https://cdn-icons-png.flaticon.com/512/1138/1138700.png"
                            style="width: 36px; height:36px;">
                    </a>
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle d-none d-md-block fw500 text-white" href="#"
                                id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Categories
                                <i class="ps-1 text-white"><svg xmlns="http://www.w3.org/2000/svg" width="16"
                                        height="16" fill="white" class="bi bi-chevron-down" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd"
                                            d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z" />
                                    </svg></i>
                            </a>
                            <ul class="dropdown-menu rounded-0 border-0" aria-labelledby="navbarDropdown">
                                {% for c in categories %}
                                <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                                    <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>


                    <div class="topnav">
                        <form class="d-flex" action="{% url 'store:search_sneaker' %}" method="POST">

                            {% csrf_token %}
                            <input type="text" name="searched" placeholder="Search" aria-label="Search" >
                        </form>
                    </div>




                    <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
                        aria-label="Toggle navigation">
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="white"
                                class="bi bi-list" viewBox="0 0 16 16">
                                <path fill-rule="evenodd"
                                    d="M2.5 11.5A.5.5 0 0 1 3 11h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 7h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 3h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z" />
                            </svg>
                        </div>
                    </button>
                    <a type="button" role="button" href="{% url "account:dashboard" %}"
                        class="btn btn-outline-secondary border-0 basket-btn">
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="33" height="33" fill="currentColor"
                                class="bi bi-person" viewBox="0 0 16 16">
                                <path
                                    d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z" />
                            </svg>
                        </div>
                    </a>


                    <a type="button" role="button" href="{% url "basket:basket_summary" %}"
                        class="btn btn-outline-secondary border-0 basket-btn">

                        {% with total_qty=basket|length %}
                        <div id="basket-qty" class="basket-qty">
                            {% if total_qty > 0 %}
                            {{ total_qty }}
                            {% else %}
                            0
                            {% endif %}
                        </div>
                        {% endwith %}
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="33" height="33" fill="currentColor"
                                class="bi bi-cart3" viewBox="0 0 16 16">
                                <path
                                    d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                            </svg>
                        </div>
                    </a>
                </div>
                <div class="d-md-none d-lg-none d-xl-none">
                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="navbar-nav me-auto mb-2 mb-md-0">
                            {% for c in categories %}
                            <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                                <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <br>
    <br>
    <div id="content" style="font-family: 'Poppins', sans-serif;">{% block content %} {% endblock %}</div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <footer class="site-footer bg-dark text-white">
        <div class="container">
          <div class="row">
            <div class="col-sm-12 col-md-6">
                <br>
                <br>
              <h6>About</h6>
              <p class="text-justify">Sneakers also called trainers, athletic shoes, tennis shoes, gym shoes, kicks, sport shoes, flats, running shoes, or runners are shoes primarily designed for sports or other forms of physical exercise, but which are now also widely used for everyday casual wear.Like other parts of the global clothing industry, manufacture of shoes is heavily concentrated in Asia with nine in ten shoes produced in that region.</p>
            </div>
    
            <div class="col-xs-6 col-md-3">
                <br>
                <br>
              <h6>Categories</h6>
              <ul class="footer-links">
                <li><a href="http://127.0.0.1:8000/shop/adidas/">ADIDAS</a></li>
                <li><a href="http://127.0.0.1:8000/shop/nike/">NIKE</a></li>
                <li><a href="http://127.0.0.1:8000/shop/fila/">FILA</a></li>
                <li><a href="#">REEBOK</a></li>
                <li><a href="#">NEW BALANCE</a></li>
                <li><a href="#">PUMA</a></li>
              </ul>
            </div>
    
            <div class="col-xs-6 col-md-3">
                <br>
                <br>
              <h6>Quick Links</h6>
              <ul class="footer-links">
                <li><a href="#">About Us</a></li>
                <li><a href="#">Contact Us</a></li>
                <li><a href="#">Contribute</a></li>
                <li><a href="#">Privacy Policy</a></li>
                <li><a href="#">Sitemap</a></li>
              </ul>
            </div>
          </div>
          <hr>
        </div>
        <div class="container">
          <div class="row">
            <div class="col-md-8 col-sm-6 col-xs-12">
              <p class="copyright-text">Copyright &copy; 2017 All Rights Reserved by 
           <a href="#">i'm Meirlan</a>.
              </p>
            </div>
    
          </div>
        </div>
    </footer>
</body>

</html>

templates/store/home.html
{% extends "./base.html" %}
{% load static %}
{% block title %}SneakerShop{% endblock %}
{% block content %}
<style>
	*{
		margin 0;
	}
	#section{
		width: 500px;
		position: absolute;
	  margin: 210px 0 0 650px;
		z-index: 1;
	}
</style>
<main>
	<section class="py-8 text-center container">
    <div class="row py-lg-6" id="section">
      <div class="col-lg-8 col-md-8 mx-auto">
        <h1 class="fw-light" style="font-size: 60px;">SneakerShop</h1>
        <p class="lead" style="font-size: 30px;">The best sneakers are only with us!</p>
        <p>
          <a href="#container" class="btn btn-primary my-2" style="font-size: 20px;">Buy sneaker</a>
        </p>
      </div>
    </div>
  </section>
	<div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel" style="position:relative; bottom: 50px;">
		<div class="carousel-inner">
			<div class="carousel-item active">
				<img src="../media/images/Sneaker.png" class="d-block w-100 " alt="" style="height: 750px;">
			</div>
		</div>
	</div>
    <div class="container" id="container">
      <div class="row justify-content-around" style="border-radius: 100px;">
        <div class="album py-5">
          <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
            {% for product in products %}
            <div class="col">
              <div class="card border-0">
                <a class="text-dark text-decoration-none"
                      href="{{ product.get_absolute_url }}"><img class="img-fluid rounded" alt="Responsive image" src="{{ product.image.url }}"></a>
                <div class="card-body px-3">
                  <p class="card-text">
                    <a class="text-dark text-decoration-none"
                      href="{{ product.get_absolute_url }}">{{ product.name|slice:":17" }}</a>
                  </p>
                  <div class="fw-bold" style="margin-top: -15px;">{{product.price}}$</div>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
</main>
{% endblock %}

templates/store/search_sneaker.html
{% extends "./base.html" %}
{% load static %}
{% block title %}SneakerShop{% endblock %}
{% block content %}

    <center>
    {%if searched%}
    <h1>You searched for {{ searched }}</h1>
    <br/>
    {%for sneaker in sneakers%}
        <a href="{{ sneaker.get_absolute_url }}"> {{  sneaker   }} - {{   sneaker.price   }} </a> <br/> 
    {%endfor%}

    {%else%}
        <h1> bad attempt, try again   </h1>

    {%endif%}

    <center>



{% endblock %}