basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('account/', include('account.urls', namespace='account')),
    path('orders/', include('orders.urls', namespace='orders')),
		path('wishlist/', include('wishlist.urls', namespace='wishlist')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_all, name='product_all'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
    path('search_sneaker/', views.search_sneaker, name='search_sneaker'),
]

wishlist/urls.py
from django.urls import path

from . import views

app_name = 'wishlist'

urlpatterns = [
    path('', views.wishlist_page, name='wishlist_page'),
    path('add/', views.wishlist_add, name='wishlist_add'),
    path('delete/', views.wishlist_delete, name='wishlist_delete'),
]

store/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='product_creator')
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', default='images/default.png')
    slug = models.SlugField(max_length=255)
    size = models.DecimalField(max_digits=2, decimal_places=0)
    price = models.DecimalField(max_digits=4, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

    def __str__(self):
        return self.name

store/views.py
from django.shortcuts import get_object_or_404, render

from .models import Category, Product


def product_all(request):
    products = Product.products.all()
    return render(request, 'store/home.html', {'products': products})


def category_list(request, category_slug=None):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(request, 'store/products/category.html', {'category': category, 'products': products})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, 'store/products/single.html', {'product': product})

def search_sneaker(request):
    if request.method == "POST":
        searched = request.POST['searched']
        sneakers = Product.objects.filter(name__contains=searched)
        return render(request, 'store/search_sneaker.html', 
        {'searched': searched,'sneakers':sneakers, } )

    else:
        return render(request, 'store/search_sneaker.html', {} )

templates/store/products/category.html
{% extends "../base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}


<main>
  <div class="container">
    <div class="row">
      <div class="album py-5">


        <div class="pb-3"><h1 class="h3">{{ category.name }}</h1></div>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

          {% for product in products %}

          <div class="col">
            <div class="card border-0">
              <a class="text-dark text-decoration-none"
                      href="{{ product.get_absolute_url }}"><img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}"></a>
              <div class="card-body px-0">
                <p class="card-text">
                  <a class="text-dark text-decoration-none"
                    href="{{ product.get_absolute_url }}">{{ product.name|slice:":17" }}</a>
                </p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="fw-bold" style="margin-top: -15px;">{{product.price}}$</div>
                </div>
              </div>
            </div>
          </div>

          {% endfor %}

        </div>
      </div>
    </div>

  </div>


</main>

{% endblock %}

templates/store/products/detail.html
{% extends "../base.html" %}

{% block content %}
<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ product.image.url }}">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ product.title }}</h1>
                <p><span class="lead">{{ product.author }}</span> (Author)</p>
                <p>{{ product.description|slice:":355" }}...</p>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">Hardback</div>
                            <div class="col-6 text-end"><span class="h4 fw-bold">£{{ product.price }}</span></div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-6">
                                <label for="select">Qty</label>
                                <select id="select">
                                    <option value="">1</option>
                                    <option value="">2</option>
                                    <option value="">3</option>
                                    <option value="">4</option>
                                </select>

                            </div>
                            <div class="col-6 text-end"><button type="button" class="btn btn-secondary btn-sm">Add to
                                    basket</button></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>
{% endblock %}

templates/store/products/single.html
{% extends "store/base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}

<style>
	#button{
		width: 150px;
		height: 45px;
		margin-left: 320px;
		margin-top: -55px;
	}
	#add-button{
		width: 300px;
		height: 45px;
	}
	.quantity_inner * {
    box-sizing: border-box;    
}    
.quantity_inner {
    display: inline-flex;
    border-radius: 26px;
    border: 4px solid #198754;
}        
.quantity_inner .bt_minus,
.quantity_inner .bt_plus,
.quantity_inner .quantity {
    height: 40px;
    width: 40px;
    padding: 0;
    border: 0;
    margin: 0;
    background: transparent;
    cursor: pointer;
    outline: 0;
}
.quantity_inner .quantity {
    width: 50px;
    text-align: center;
    font-size: 30px;
    font-weight: bold;
    color: #000;
    font-family: Menlo,Monaco,Consolas,"Courier New",monospace;
}
.quantity_inner .bt_minus svg,
.quantity_inner .bt_plus svg {
    stroke: #198754;
    stroke-width: 4;
    transition: 0.5s;
    margin: 10px;
}    
.quantity_inner .bt_minus:hover svg,
.quantity_inner .bt_plus:hover svg {
    stroke: #000;
}
</style>

<main class="pt-2">

  <div class="container" style="max-width: 1000px">
    <div class="row g-3">   
        <div class="col-12 d-flex justify-content-between">
        </div>
        <div class="col-md-5 ps-3 col-lg-5 order-md-last p-0 order-1">
            <div class="d-grid gap-2">
							<h1 class="mb-0 h2 pe-4 pb-4">{{ product.name }}</h1>
            <hr>
            <p id="text-desc" >{{product.description}}</p>
            <hr>
						<div class="d-flex d-flex-inline justify-content-between">
							<div><span class="h3">{{ product.price }}$</span></div>
										 <div class="">
																	<label for="select">Quantity</label>
																	<select id="select" class="h6" style="width:50px;height:40px;">
																			<option value="1">1</option>
																			<option value="2">2</option>
																			<option value="3">3</option>
																			<option value="4">4</option>
																	</select>
											</div>
							</div>
            <button type="button" id="add-button" value="{{product.id}}" class="btn btn-primary fw500">Add to basket</button>
						{% if product.wishlist_add %}
						<button type="button" class="btn btn-small" id="button" value="{{product.id}}">
							<svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="red" class="bi bi-heart-fill" viewBox="0 0 19 16">
								<path fill-rule="evenodd" d="M8 1.314C12.438-3.438 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
							</svg></button>
						{% else %}
						<button type="button" class="btn btn-small" id="button" value="{{product.id}}">
							<svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 19 16">
								<path fill-rule="evenodd" d="M8 1.314C12.438-3.438 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
							</svg></button>
						{% endif %}
            </div>
        </div>
        <div class="col-md-7 col-lg-7 p-0">
            <div class="card mb-3 border-0">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-body p-1" style="background-color: #E3E2DF;">                       
                        <div><img class="img-fluid mx-auto d-block" width="300px" alt="Responsive image" src="{{ product.image.url }}"></div>
                    </div>
                </div>
            </div>
            </div>     
        </div>
    </div>
  </div>
</main>

<script>
    $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_add" %}',
            data: {
                productid: $('#add-button').val(),
                productqty: $('#select option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
               document.getElementById("basket-qty").innerHTML = json.qty
            },
            error: function (xhr, errmsg, err) {}
        });
    })
		$(document).on('click', '#button', function (e) {
			e.preventDefault();
			$.ajax({
					type: 'POST',
					url: '{% url "wishlist:wishlist_add" %}',
					data: {
							productid: $('#button').val(),
							productqty: $('#select option:selected').text(),
							csrfmiddlewaretoken: "{{csrf_token}}",
							action: 'post'
					},
					success: function (json) {
						 document.getElementById("wishlist-qty").innerHTML = json.qty
					},
					error: function (xhr, errmsg, err) {}
			});
	})
</script>

{% endblock %}